### ISSUE TITLE
Project freezes after conversion

### ISSUE THREAD

**Issue by RexScratch** [jahunsbe1/sb3tosb2#4]
See the "game" custom block in the "Game" sprite in the project below
[project.zip](https://github.com/jahunsbe1/sb3tosb2/files/2877296/project.zip)

**Comment by BirdLogics** [comment]
It seems to be working correctly, the game custom block has no refresh disabled after converting. Is it supposed to be enabled?

**Comment by RexScratch** [comment]
No, you're correct. It's still freezing when you click the play for some reason, though...

**Comment by BirdLogics** [comment]
I found out that sometimes list contents were being lost causing this issue. It should be fixed now though I still need to look more exactly into why it was happening.
