### ISSUE TITLE
"-Infinity" and "Infinity" strings are not converted to floats

### ISSUE THREAD

**Issue by RexScratch** [jahunsbe1/sb3tosb2#5]
This is a really subtle issue, but `"-Infinity"` and `"Infinity"` should be converted to `float('-inf')` and `float('inf')`. Not doing so can cause some equality issues with Scratch 2.0 (but not 3.0) since it tries to compare `"-Infinity"` and `"Infinity"` as if they were strings, resulting in `"-Infinity" > -1` returning true, when it should obviously be false.

**Comment by BirdLogics** [comment]
Ok, this should be fixed. One tricky thing with it is that if the project was originally made in 2.0, the user would not expect Infinity strings to convert to Infinity, such as when typed in lists or set blocks. Currently it checks and converts variables, lists, and string inputs.
