### ISSUE TITLE
wedo2 opcodes are converted incorrectly

### ISSUE THREAD

**Issue by RexScratch** [jahunsbe1/sb3tosb2#6]
wedo2 opcodes are converted to undefined blocks despite being included in the specmap.

**Comment by RexScratch** [comment]
It appears that this is due to the extension data not being added. Adding the extension after opening the sb2 will convert all wedo2 undefined blocks into the correct WeDo 2.0 blocks.

**Comment by BirdLogics** [comment]
Extension information is now added. I made it only add the extension name and it seems to automatically retrieve the specs.
